# Generated by Django 3.1 on 2020-08-18 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('myApt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roomate_app.apartment')),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
