# Generated by Django 3.1 on 2020-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0003_chore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
