# Generated by Django 3.1 on 2020-08-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0007_auto_20200820_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='w7phH1hqR1RXIOTh_2Bafg', max_length=100),
        ),
    ]
