# Generated by Django 3.1 on 2020-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0008_auto_20200820_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='o-eaupaVHolWyR_ExwlHXQ', max_length=100),
        ),
    ]
