# Generated by Django 3.1 on 2020-08-20 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0009_auto_20200820_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='apt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomate_app.apartment'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='0fb9398311908671626f666b40b470b7d33bf024', max_length=100),
        ),
    ]
