# Generated by Django 3.1 on 2020-08-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0010_auto_20200820_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='apt',
            new_name='apt_id',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='a15af3e05657fa0e566c2eeadfb0d529fe4de618', max_length=100),
        ),
    ]
