# Generated by Django 3.1 on 2020-08-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0011_auto_20200820_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='aef4ba5690e7f892538a3290c9d3579f66bece8d', max_length=100),
        ),
    ]
