# Generated by Django 3.1 on 2020-08-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0012_auto_20200821_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='16a07325a1281c2e29c08c175b95ad9ffa5da358', max_length=100),
        ),
    ]
