# Generated by Django 3.1 on 2020-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0013_auto_20200821_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='description',
            field=models.CharField(default='Description of Chore', max_length=500),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='00b1a25a77ac362ea266cee6e62f45b05ce28f7e', max_length=100),
        ),
        migrations.RemoveField(
            model_name='chore',
            name='assignees',
        ),
        migrations.AddField(
            model_name='chore',
            name='assignees',
            field=models.ManyToManyField(to='roomate_app.MyUser'),
        ),
    ]
