# Generated by Django 3.1 on 2020-08-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0014_auto_20200821_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='assignees',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='f44e15f93231b9cfbe60f6a103e38ccc79f50ad9', max_length=100),
        ),
        migrations.AlterField(
            model_name='chore',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomate_app.myuser'),
        ),
    ]
