# Generated by Django 3.1 on 2020-08-23 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomate_app', '0015_auto_20200822_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assignees',
            field=models.ManyToManyField(to='roomate_app.MyUser'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='3f9bc5967ae776ddbfa7a594dd8ddcc80d5aed71', max_length=100),
        ),
        migrations.AlterField(
            model_name='chore',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
