# Generated by Django 3.1 on 2020-08-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0016_auto_20200823_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='f8a0df3e2710da749091374ab30ffa7e875bf120', max_length=100),
        ),
    ]
