# Generated by Django 3.1 on 2020-08-24 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomate_app', '0019_auto_20200823_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='94f2be12871868192bf00f1ddedd0b86be5c44b4', max_length=100),
        ),
        migrations.AlterField(
            model_name='chore',
            name='assignees',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
