# Generated by Django 3.1 on 2020-08-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0020_auto_20200824_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='bff6ccf6cba4d4966edd139e4d87e2de3380ac34', max_length=100),
        ),
    ]
