# Generated by Django 3.1 on 2020-08-25 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomate_app', '0020_auto_20200824_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='5d026a808b96f9e1328e867d470dd15043b099e4', max_length=100),
        ),
        migrations.AlterField(
            model_name='chore',
            name='assignees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
