# Generated by Django 3.1 on 2020-08-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0021_auto_20200825_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='193d2e1479b768cf733821ebf8b30887301f41b5', max_length=100),
        ),
    ]
