# Generated by Django 3.1 on 2020-08-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0023_auto_20200825_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='token',
        ),
    ]
