# Generated by Django 3.1 on 2020-08-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomate_app', '0025_apartment_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='token',
            field=models.CharField(default='Sr4IdCBPw8IJAIG4', max_length=100),
        ),
    ]
